# 应用名称
spring:
  application:
    name: bookServer
  datasource:
    driver-class-name: com
    url: jdbc:mysql://localhost:3306/book?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: admin
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 15
      idle-timeout: 180000
      maximum-pool-size: 10000
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1


